### ISSUE TITLE
Season average stats wrong because missed games are not being accounted for

### ISSUE THREAD

**Issue by asucaden** [ynnadkrap/balldontlie#103]
Every player's "games_played" is set to the total amount of games their team has played.

For example Ja Morant has missed 5 games this season but /season_averages says he has played in all 29 (as of 12/19/2022).

Another example - Cam Johnson has missed a ton of games this season.  He has played in only 8 games this season.  /season_averages says he has played 30, which causes balldontlie to list his season averages at ~30% of their true values.

![Ja Stats](https://user-images.githubusercontent.com/56139352/208522603-886011e1-d12e-4b7c-9c8e-013554ed650a.PNG)
![Cam Johnson Stats](https://user-images.githubusercontent.com/56139352/208522613-f88f4102-ad3d-4795-8bb9-ec4a750706cd.PNG)

**Comment by erdemduman** [comment]
I can also approve that. Total stats are directly divided by the number of games played this season. Players missing games is not taken into consideration.

**Comment by ynnadkrap** [comment]
this should be fixed now

**Comment by asucaden** [comment]
Works for me :)

**Comment by erdemduman** [comment]
It is working. Thank you!
