### ISSUE TITLE
Stats for multiple players

### ISSUE THREAD

**Issue by cailborg** [ynnadkrap/balldontlie#11]
More of a question than an issue, but is there a reason you set it up to have multiple players joined by & and not just within one single player_ids array? What is the empty array after each player_id for? Can work around the implementation but was just curious!

Current
api/v1/season_averages?season=2018&player_ids[]=1&player_ids[]=2

Example
api/v1/season_averages?season=2018&player_ids=[1, 2]

**Comment by jharrilim** [comment]
I think that might just be how ruby handles query params: https://guides.rubyonrails.org/action_controller_overview.html#hash-and-array-parameters

If you'd like to see how I handled this, check here: https://github.com/jharrilim/balldontlie-client/blob/master/src/api/v1/index.ts#L11

**Comment by ynnadkrap** [comment]
It depends on the framework. As jharrilim said above, rails expects `foo[]=1&foo[]=2`. Here's some good info: https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string

**Comment by cailborg** [comment]
Excellent, thanks for the info guys, will dive into rails a bit more!
