### ISSUE TITLE
Stats not updating

### ISSUE THREAD

**Issue by nealmick** [ynnadkrap/balldontlie#112]
It appears as though game scores have stopped updating.  Just noticed yesterday. Thanks for any help and all the work on this project.  I truly appreciate it.

example game from yesterday, no scores:
https://www.balldontlie.io/api/v1/games/858210

same game:
https://www.espn.com/nba/game/_/gameId/401469010

**Comment by ynnadkrap** [comment]
oops, this should be fixed now. thanks for reporting
