### ISSUE TITLE
Game stats not updated

### ISSUE THREAD

**Issue by adampagels** [ynnadkrap/balldontlie#22]
As of yesterday (2020-01-29) game scored are not being updated. When viewing games for the 29th and today (the 30th), scores are at 0 and the status shows the time of the game despite already being completed/in progress.

**Comment by Toma4205** [comment]
3 days in a row now. Any information please?

**Comment by ynnadkrap** [comment]
Thanks for bringing this up. I'll take a look sometime this week.

**Comment by adampagels** [comment]
@ynnadkrap Thanks a lot!

**Comment by ynnadkrap** [comment]
This should be fixed now. Gonna close issue.
