### ISSUE TITLE
Adding games to stats where players played 0 minutes

### ISSUE THREAD

**Issue by wallstarr** [ynnadkrap/balldontlie#23]
For players of the current season, there are some games in the stats portion of the API where a player played 0 minutes. This is affecting season averages of the players because these games are being counted as games played, so all per game statistical categories are being deflated. 

Example: As of 2/6/2020, Beal is averaging 29.2 ppg, but the season average being retrieved is 26.63 since there are four games added to his stats where he played 0 minutes (ie: didn't play.)

**Comment by ynnadkrap** [comment]
Thanks for pointing this out. This should be fixed now.
