### ISSUE TITLE
Data not matching stats.nba.com

### ISSUE THREAD

**Issue by cailborg** [ynnadkrap/balldontlie#3]
Just noticed a few discrepancies with some stats.
Example I've used is James Harden's season totals. I'm grabbing his stats/per game and adding them all together with a loop to get the season total, but a few of the stats (blocks, steals and rebounds) are off by one or two points.

I'm definitely getting all the games (have the results per page set to a conservative 100), so is there a possibility some game data hasn't been recorded properly?

Here's the link to his 2018-2019 season totals on stats.nba.com [https://stats.nba.com/player/201935/?Season=2018-19&SeasonType=Regular%20Season&PerMode=Totals](James Harden)

and a screenshot of my console output showing total points, rebounds, assists, steals, blocks & turnovers
![Screen Shot 2019-04-15 at 11 16 16 am](https://user-images.githubusercontent.com/5325545/56102407-4465aa00-5f70-11e9-9c5e-ffe47cc35f1a.png)

**Comment by ynnadkrap** [comment]
Thanks for pointing this out. Looks like I accidentally forgot to mark this season's postseason games, so those games were counting as regular season games. The problem should be fixed now though.
