### ISSUE TITLE
Players on the Wrong Team

### ISSUE THREAD

**Issue by chesterjzara** [ynnadkrap/balldontlie#4]
Hello,

I noticed an issue where player teams aren't updated in at least one instance. So far I am only seeing this for Tyler Zeller but if I find more examples I will add them here.

[Players search API call](https://www.balldontlie.io/api/v1/players?search=zeller)
[Bball Ref page](https://www.basketball-reference.com/players/z/zellety01.html)

**Comment by ynnadkrap** [comment]
Thanks for pointing this out. I'll take care of this sometime this week.

**Comment by chesterjzara** [comment]
Another example - Jeremy Lin is listed as on the Atlanta Hawks still.

Let me know if its not helpful to keep adding examples I find.

**Comment by ynnadkrap** [comment]
@chesterjzara this should be fixed now.

**Comment by ChrisKatsaras** [comment]
I've noticed Chris Bosh falls victim to this issue as well

**Comment by ChrisKatsaras** [comment]
In light of all the recent signings/trades, will there be an update coming for player data in the near future or is the plan to wait until free agency has cooled down a bit @ynnadkrap?

**Comment by ynnadkrap** [comment]
The data source hasn't updated to reflect the changes. I'll hunt around for another source or wait until the current one gets refreshed. Either way, I'll let you know when it's updated.

**Comment by ChrisKatsaras** [comment]
Sounds good and thanks a lot for the quick response! Your work is really appreciated

**Comment by ChrisKatsaras** [comment]
Any update on when the data source will be refreshed again, @ynnadkrap?

**Comment by ynnadkrap** [comment]
It should be refreshing regularly. Can you show me an example that's showing incorrect results? @ChrisKatsaras

**Comment by ChrisKatsaras** [comment]
It looks like this was a false alarm on my end @ynnadkrap ! Sorry about that and thanks for the quick response 💯
