### ISSUE TITLE
`/games` stopped returning the right games (as of 2020-08-25)

### ISSUE THREAD

**Issue by omkarmoghe** [ynnadkrap/balldontlie#44]
here's the 24th which looks good: https://www.balldontlie.io/api/v1/games?dates[]=2020-08-24
vs https://www.espn.com/nba/scoreboard/_/date/20200824

here's the 25th where the `status` is empty and the games themselves don't look right: https://www.balldontlie.io/api/v1/games?dates[]=2020-08-24
vs https://www.espn.com/nba/scoreboard/_/date/20200825

Thanks!

**Comment by ynnadkrap** [comment]
hmm, i think it looks ok. let me know if im missing something. feel free to close otherwise.

**Comment by omkarmoghe** [comment]
@ynnadkrap yeah was getting weird data for a day but it looks fine now.
