### ISSUE TITLE
Structure for getting 2020 games different?

### ISSUE THREAD

**Issue by treyg** [ynnadkrap/balldontlie#51]
Is the link structure for getting games for this season different than last? I'm able to get last seasons games still with this structure: `https://www.balldontlie.io/api/v1/games?seasons[]=2019&team_ids[]=9&per_page=82`

But when I switch out the 2019 for 2020 I'm getting an empty array. 

Thanks!

**Comment by alexfayad** [comment]
The original data source only pulls games before they happen, it doesn't pull all games for the upcoming season.

**Comment by alexfayad** [comment]
I'd expect the night before or day of the season starting, the dataset will be updated.

**Comment by BaronBeans** [comment]
Any news on this? I was expecting to start seeing the data today?

**Comment by ynnadkrap** [comment]
Updated

**Comment by treyg** [comment]
> Updated

Thank you!

**Comment by adamsulimadolina** [comment]
Hi, I can see that except 2 first days of season, game data is not updated. Any chances for fix?
