### ISSUE TITLE
Seems that stats and game data is missing for 2021-01-12

### ISSUE THREAD

**Issue by BaronBeans** [ynnadkrap/balldontlie#55]
According to NBA.com the following games happened on the 12th Jan:
Heat 134 - 137 76ers
Nuggets 116 - 122 Nets
Jazz 117 - 87 Cavaliers
Lakers 117 - 100 Rockets
Spurs 112 - 102 Thunder
Pacers 104 - 95 Warriors

However there is no data returned from [https://balldontlie.io/api/v1/stats?dates[]=2021-01-12](https://balldontlie.io/api/v1/stats?dates[]=2021-01-12) or [https://balldontlie.io/api/v1/games?dates[]=2021-01-12](https://balldontlie.io/api/v1/games?dates[]=2021-01-12)

**Comment by ynnadkrap** [comment]
Sorry about this. In addition to this problem, there's no data being collected right now. I'll fix it this weekend.

**Comment by ljolliet** [comment]
There is also no data on the 14th and no update on the 15th
