### ISSUE TITLE
Season average percentage off by 100%

### ISSUE THREAD

**Issue by BostonRohan** [ynnadkrap/balldontlie#67]
Season average percentages: field goal, three-point, and free throw are 100% less than the actual percentage. 

Ex: fg_pct: 0.52 instead of actual percentage 52.0.

**Comment by treyg** [comment]
I think that's generally how stats are provided. If you want to display it as a non-decimal, why not just multiply it by 100?

**Comment by BostonRohan** [comment]
I see, I did just end up multiplying by 100 but I figured that there was an error in the calculation. 

My apologizes.
