### ISSUE TITLE
New Season Scores

### ISSUE THREAD

**Issue by nealmick** [ynnadkrap/balldontlie#91]
The new season has started and it appears as though game stats are not updating.

Example no updated game stats from yesterday 10-18-22:
https://www.balldontlie.io/api/v1/games/857356

Same game:
https://www.nba.com/game/lal-vs-gsw-0022200002/box-score

appreciate any insights

**Comment by ynnadkrap** [comment]
it looks like the endpoints changed. give me a few days to fix this.

**Comment by ynnadkrap** [comment]
we're back baby 🚀

**Comment by nealmick** [comment]
No way i just checked.  Everything is working perfectly!! thanks a bunch!!!
